terminal_source: ''
software_timer:
  priority: 2
  stack_depth: 1024
SPI:
  spi2:
    tx_buffer_size: 32
    rx_buffer_size: 32
    dma_section: ''
    dma_enable_min_size: 3
  spi6:
    tx_buffer_size: 32
    rx_buffer_size: 32
    dma_section: ''
    dma_enable_min_size: 3
USART:
  usart1:
    tx_buffer_size: 128
    rx_buffer_size: 128
    dma_section: ''
    tx_queue_size: 5
  usart2:
    tx_buffer_size: 128
    rx_buffer_size: 128
    dma_section: ''
    tx_queue_size: 5
  usart3:
    tx_buffer_size: 128
    rx_buffer_size: 128
    dma_section: ''
    tx_queue_size: 5
  usart6:
    tx_buffer_size: 128
    rx_buffer_size: 128
    dma_section: ''
    tx_queue_size: 5
  uart5:
    tx_buffer_size: 128
    rx_buffer_size: 128
    dma_section: ''
    tx_queue_size: 5
  uart8:
    tx_buffer_size: 128
    rx_buffer_size: 128
    dma_section: ''
    tx_queue_size: 5
  uart7:
    tx_buffer_size: 128
    rx_buffer_size: 128
    dma_section: ''
    tx_queue_size: 5
FDCAN:
  FDCAN1:
    queue_size: 5
  FDCAN2:
    queue_size: 5
  FDCAN3:
    queue_size: 5
USB:
  usb_device:
    enable: false
  usb_otg_hs:
    enable: false
  usb_fs:
    enable: false
Terminal:
  read_buff_size: 32
  max_line_size: 32
  max_arg_number: 5
  max_history_number: 5
SYSTEM: FreeRTOS
FlashLayout:
  model: STM32H723VGT6
  flash_base: '0x08000000'
  flash_size_kb: 1024
  sectors:
  - index: 0
    address: '0x08000000'
    size_kb: 128.0
  - index: 1
    address: '0x08020000'
    size_kb: 128.0
  - index: 2
    address: '0x08040000'
    size_kb: 128.0
  - index: 3
    address: '0x08060000'
    size_kb: 128.0
  - index: 4
    address: '0x08080000'
    size_kb: 128.0
  - index: 5
    address: '0x080A0000'
    size_kb: 128.0
  - index: 6
    address: '0x080C0000'
    size_kb: 128.0
  - index: 7
    address: '0x080E0000'
    size_kb: 128.0
