terminal_source: uart7
software_timer:
  priority: 2
  stack_depth: 4096
SPI:
  spi2:
    tx_buffer_size: 32
    rx_buffer_size: 32
    dma_section: ''
    dma_enable_min_size: 3
  spi6:
    tx_buffer_size: 64
    rx_buffer_size: 32
    dma_section: ''
    dma_enable_min_size: 64
USART:
  usart1:
    tx_buffer_size: 128
    rx_buffer_size: 128
    dma_section: ''
    tx_queue_size: 5
  usart2:
    tx_buffer_size: 128
    rx_buffer_size: 128
    dma_section: ''
    tx_queue_size: 5
  usart3:
    tx_buffer_size: 128
    rx_buffer_size: 128
    dma_section: ''
    tx_queue_size: 5
  usart6:
    tx_buffer_size: 128
    rx_buffer_size: 128
    dma_section: ''
    tx_queue_size: 5
  uart5:
    tx_buffer_size: 128
    rx_buffer_size: 128
    dma_section: ''
    tx_queue_size: 5
  uart8:
    tx_buffer_size: 128
    rx_buffer_size: 128
    dma_section: ''
    tx_queue_size: 5
  uart7:
    tx_buffer_size: 128
    rx_buffer_size: 128
    dma_section: ''
    tx_queue_size: 5
FDCAN:
  FDCAN1:
    queue_size: 5
  FDCAN2:
    queue_size: 5
  FDCAN3:
    queue_size: 5
USB:
  usb_device:
    enable: false
  usb_otg_hs:
    enable: false
  usb_fs:
    enable: false
Terminal:
  read_buff_size: 32
  max_line_size: 32
  max_arg_number: 5
  max_history_number: 5
  run_as_thread: false
SYSTEM: FreeRTOS
FlashLayout:
  model: STM32H723VGT6
  flash_base: '0x08000000'
  flash_size_kb: 1024
  sectors:
  - index: 0
    address: '0x08000000'
    size_kb: 128.0
  - index: 1
    address: '0x08020000'
    size_kb: 128.0
  - index: 2
    address: '0x08040000'
    size_kb: 128.0
  - index: 3
    address: '0x08060000'
    size_kb: 128.0
  - index: 4
    address: '0x08080000'
    size_kb: 128.0
  - index: 5
    address: '0x080A0000'
    size_kb: 128.0
  - index: 6
    address: '0x080C0000'
    size_kb: 128.0
  - index: 7
    address: '0x080E0000'
    size_kb: 128.0
device_aliases:
  CS1_ACCEL:
    type: GPIO
    aliases:
    - CS1_ACCEL
    - bmi088_accl_cs
  CS1_GYRO:
    type: GPIO
    aliases:
    - CS1_GYRO
    - bmi088_gyro_cs
  INT1_GYRO:
    type: GPIO
    aliases:
    - INT1_GYRO
    - bmi088_gyro_int
  spi2:
    type: SPI
    aliases:
    - spi2
    - spi_bmi088
  pwm_tim12_ch2:
    type: PWM
    aliases:
    - Buzzer
    - pwm_buzzer
    - pwm_tim12_ch2
  power_manager:
    type: PowerManager
    aliases:
    - power_manager
  INT1_ACCEL:
    type: GPIO
    aliases:
    - INT1_ACCEL
  spi6:
    type: SPI
    aliases:
    - Light
    - spi6
  usart1:
    type: UART
    aliases:
    - usart1
  usart2:
    type: UART
    aliases:
    - usart2
  usart3:
    type: UART
    aliases:
    - usart3
  usart6:
    type: UART
    aliases:
    - usart6
  uart5:
    type: UART
    aliases:
    - uart5
  uart8:
    type: UART
    aliases:
    - uart8
  uart7:
    type: UART
    aliases:
    - uart7
  fdcan1:
    type: FDCAN
    aliases:
    - fdcan1
  fdcan2:
    type: FDCAN
    aliases:
    - fdcan2
  fdcan3:
    type: FDCAN
    aliases:
    - fdcan3
  ramfs:
    type: RamFS
    aliases:
    - ramfs
  terminal:
    type: Terminal<32, 32, 5, 5>
    aliases:
    - terminal
  pwm_tim3_ch4:
    type: PWM
    aliases:
    - pwm_bmi088_heat
    - pwm_tim3_ch4
